### PR TITLE
Fix dart ci badge

### PR DESCRIPTION
**Pull request by adripo**
fix: #198

### CODE REVIEW

**Comment by guyluz11** [comment]
Please re open pr to dev branch

**Comment by adripo** [comment]
@guyluz11 I see that someone else already merged the solution to dev branch, so I will close my PR.

**Comment by adripo** [comment]
@guyluz11 can you please add `hacktoberfest-accepted` label if you consider that my change was correct?

**Comment by guyluz11** [comment]
Thanks for letting me know, I forgot to close it.

Unforently I don't think I can count it as accepted as it didn't get merged :(

But since you asked so nicely let me offer you a new issue 
https://github.com/CyBear-Jinni/security_bear/issues/73

I will add to it Hactoberfest tag tomorrow so that you will have time to open pr for it :)

**Comment by adripo** [comment]
@guyluz11 thank you for the opportunity, I will check the new issue today

**Pull request closed without merging**
