### PR TITLE
issue #175 : upgrading the dependencies 

### PR DESCRIPTION
**Pull request by superiorsd10**
#175 
I've updated the dependencies to the latest version without any dependencies issues constraints. There is some dependency that I've not updated because another dependency depends on their lower versions. So it'll create a major problem in version solving.

### CODE REVIEW

**Comment by guyluz11** [comment]
Can you open the piano to Dev Branch please?

**Comment by superiorsd10** [comment]
@guyluz11 Yeah! Sure!

**Comment by superiorsd10** [comment]
@guyluz11 I'm trying to open a pull request to the dev branch, but there are 25 other commits also there that are been included!

**Comment by guyluz11** [comment]
Yep you should fork dev or marge dev to your branch

**Pull request closed without merging**
